### ISSUE TITLE
Mavericks

### ISSUE THREAD

**Issue by akeddy** [beiko-lab/gengis#45]
GenGIS will not currently compile on OS X 10.9.
This issue seems to be the head of it:
../../../i386/library3rd/wxPython/include/wx-2.8/wx/db.h:83:22: fatal error:
      'sql.h' file not found
            #include <sql.h>
